# Generated by Django 3.1 on 2020-08-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('record_label', models.CharField(max_length=50)),
                ('release_year', models.DateField()),
            ],
        ),
    ]
