# Generated by Django 3.1 on 2020-09-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200902_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='listening',
            name='whole',
            field=models.BooleanField(default=False),
        ),
    ]
