# Generated by Django 3.1 on 2020-09-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200905_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='musicians',
            field=models.ManyToManyField(to='main_app.Musician'),
        ),
    ]
